Add UW venue info
pdxrconf/pdxrconf.github.io pull request #149
Opened 2024-02-26 22:30 UTC by kdillmcfarland

2024-02-26 23:34 UTC, jadeynryan approved these changes
Committed a few minor changes:
-  I prefer being explicit (University of Washington instead of U of Washington)
-  couple typos
-  fixed UW google map link.

2024-02-26 23:37 UTC, jadeynryan requested changes
Just realized the Venue button in the navbar still goes to the more info coming soon venue page (https://deploy-preview-149--brave-albattani-75ca02.netlify.app/coming_soon/venue/)

2024-02-26 23:43 UTC, jadeynryan approved these changes

2024-02-27 00:26 UTC, kdillmcfarland commented
> Just realized the Venue button in the navbar still goes to the more info coming soon venue page (https://deploy-preview-149--brave-albattani-75ca02.netlify.app/coming_soon/venue/)

Yes, I had not turned this on yet because I don't want it live to the website until we have a tickets page as well.

2024-02-27 00:54 UTC, merged